#!/usr/bin/env bash
# Read-only hardware triage for running the RX3 `rbp` (ARM32 soft-float) on this board.
# Writes a markdown report; changes nothing on the system. Safe to run as a normal user.
set -uo pipefail

SELF_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="${1:-$SELF_ROOT/docs/sessions/$(date +%F)-board-triage.md}"
mkdir -p "$(dirname "$OUT")"
sec() { printf '\n## %s\n\n' "$1"; }
run() { printf '```\n$ %s\n' "$*"; eval "$*" 2>&1 | head -40; printf '```\n'; }

{
echo "# Board triage $(date -Is) on $(hostname)"
echo "Read-only report generated by scripts/orangepi/board-triage.sh. Review before sharing (hostname and kernel log lines are included)."

sec "1. CPU and AArch32 (can the board run ARM32 EABI5?)"
run "uname -m; uname -r"
run "lscpu | grep -E 'Model name|Architecture|CPU op-mode|Core|Thread|Vendor' "
run "ls /sys/devices/system/cpu/aarch32_el0 2>&1 && cat /sys/devices/system/cpu/aarch32_el0"
run "(zcat /proc/config.gz 2>/dev/null || cat /boot/config-\$(uname -r) 2>/dev/null) | grep -E 'COMPAT|AARCH32|ARM64_ILP32|PREEMPT|RT_GROUP_SCHED|DRM_FBDEV|FB_DEVICE'"
if [ -x ./hello32 ]; then run "./hello32"; else echo "(no ./hello32; build a static ARM32 test binary to confirm execve works)"; fi

sec "2. Real-time scheduling (rbp needs it)"
run "cat /proc/sys/kernel/sched_rt_runtime_us /proc/sys/kernel/sched_rt_period_us"
run "ulimit -r"

sec "3. Display (rbp uses fbdev/DRM, UI 1280x800)"
run "ls -l /dev/fb* /dev/dri/ 2>&1"
run "cat /sys/class/graphics/fb0/virtual_size /sys/class/graphics/fb0/bits_per_pixel 2>&1"
run "for c in /sys/class/drm/card*-*; do echo \"\$c \$(cat \$c/status 2>/dev/null) \$(head -1 \$c/modes 2>/dev/null)\"; done"

sec "4. Audio (ALSA)"
run "aplay -l"
run "cat /proc/asound/cards"
run "ls /dev/snd"

sec "5. Input and touch"
run "ls /dev/input"
run "grep -E 'Name=|Handlers=' /proc/bus/input/devices | paste - - | head -20"

sec "6. USB (library stick and DDJ-400 power)"
run "lsusb -t"
run "lsusb | grep -i -E 'pioneer|ddj|hub|mass|storage'"
run "dmesg 2>&1 | grep -i -E 'usb|otg|vbus|over-current' | tail -15"

sec "7. Memory and storage"
run "free -m"
run "df -h / /home 2>&1"

sec "8. Toolchain for soft-float shims"
run "command -v arm-linux-gnueabi-gcc arm-linux-gnueabihf-gcc gcc shellcheck jq 2>&1"
run "ls /lib/ld-linux* /lib/arm-linux-gnueabi* 2>&1 | head"
} > "$OUT"

echo "report: $OUT"
