#!/usr/bin/env bash
# Run ON the Orange Pi: (1) can it execute a soft-float ARM32 EABI5 binary (like rbp), and
# (2) is SCHED_FIFO real-time allowed for that 32-bit process: as the user, as root, and inside a
# systemd service (where CONFIG_RT_GROUP_SCHED can still deny it). Writes a markdown report.
#
# Usage: test-arm32-rt.sh [--sudo] [report.md]
#   no flag : unprivileged only (build, run, report RT state). Changes nothing.
#   --sudo  : also (a) sets kernel.sched_rt_runtime_us=-1 temporarily and restores the old value on exit,
#             (b) runs the test binary as root, (c) runs it as your user in a transient systemd unit with
#             LimitRTPRIO=99. Each privileged command is printed first; sudo will ask for your password.
# Env:   RUNNER  command prefix for the binary (testing only, e.g. qemu-arm).
set -uo pipefail

USE_SUDO=0
[ "${1:-}" = "--sudo" ] && { USE_SUDO=1; shift; }
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
OUT="${1:-$ROOT/docs/sessions/$(date +%F)-arm32-rt-test.md}"
mkdir -p "$(dirname "$OUT")"
WORK="$(mktemp -d)"
RUNNER="${RUNNER:-}"
OLD_RT=""
cleanup() {
  if [ -n "$OLD_RT" ]; then sudo sysctl -q -w "kernel.sched_rt_runtime_us=$OLD_RT" >/dev/null 2>&1 && echo "restored kernel.sched_rt_runtime_us=$OLD_RT" >&2; fi
  rm -rf "$WORK"
}
trap cleanup EXIT
trap 'exit 130' INT TERM

R=""; add() { R="$R$*"$'\n'; }
sec() { add ""; add "## $1"; add ""; }
run() {  # run <cmd> [args...]: record command, output (max 60 lines) and exit code; sets LAST_RC
  local out; out="$("$@" 2>&1)"; LAST_RC=$?
  add '```'; add "\$ $*"; add "$(printf '%s\n' "$out" | head -60)"; add "[exit $LAST_RC]"; add '```'
}
verdict() { add "- **$1**: $2"; printf '%-34s %s\n' "$1" "$2"; }

cat > "$WORK/hello32.c" <<'EOF'
#define _GNU_SOURCE
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <sched.h>
#include <time.h>
#include <unistd.h>
int main(void) {
  struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);
  printf("hello32: long=%zu ptr=%zu time_t=%zu pid=%d mono=%ld.%09ld uid=%d\n",
         sizeof(long), sizeof(void *), sizeof(time_t), (int)getpid(), (long)ts.tv_sec, ts.tv_nsec, (int)getuid());
  struct sched_param sp; memset(&sp, 0, sizeof sp); sp.sched_priority = 50;
  if (sched_setscheduler(0, SCHED_FIFO, &sp) == 0) {
    printf("SCHED_FIFO prio 50: OK (policy=%d)\n", sched_getscheduler(0)); return 0;
  }
  printf("SCHED_FIFO prio 50: DENIED errno=%d (%s)\n", errno, strerror(errno)); return 3;
}
EOF

add "# ARM32 + real-time test $(date -Is) on $(hostname)"
add "Generated by scripts/orangepi/test-arm32-rt.sh (privileged steps: $([ $USE_SUDO -eq 1 ] && echo enabled || echo disabled))."

sec "1. Toolchain and build (soft-float EABI5, same flags as the RX3 shims)"
if ! command -v arm-linux-gnueabi-gcc >/dev/null; then
  add "arm-linux-gnueabi-gcc not found. Install: sudo apt-get install -y gcc-arm-linux-gnueabi libc6-dev-armel-cross"
  printf '%s\n' "$R" > "$OUT"; echo "report: $OUT"; exit 1
fi
run arm-linux-gnueabi-gcc -O2 -static -march=armv5t -mfloat-abi=soft -fno-stack-protector -o "$WORK/hello32" "$WORK/hello32.c"
[ $LAST_RC -eq 0 ] || { printf '%s\n' "$R" > "$OUT"; echo "static build failed; report: $OUT"; exit 1; }
DYN=0
run arm-linux-gnueabi-gcc -O2 -march=armv5t -mfloat-abi=soft -fno-stack-protector -o "$WORK/hello32-dyn" "$WORK/hello32.c"
[ $LAST_RC -eq 0 ] && DYN=1
run readelf -h "$WORK/hello32"

sec "2. Execute the ARM32 binary as the current user ($(id -un))"
# shellcheck disable=SC2086
run $RUNNER "$WORK/hello32"; RC_STATIC=$LAST_RC
RC_DYN="skipped"
if [ $DYN -eq 1 ]; then
  add "Dynamic soft-float build (needs /lib/ld-linux.so.3 and the armel libc on the host):"
  # shellcheck disable=SC2086
  run $RUNNER "$WORK/hello32-dyn"; RC_DYN=$LAST_RC
fi

sec "3. Real-time state before any change"
run cat /proc/sys/kernel/sched_rt_runtime_us /proc/sys/kernel/sched_rt_period_us
run bash -c 'ulimit -r; ulimit -e'
run bash -c 'zcat /proc/config.gz 2>/dev/null | grep -E "RT_GROUP_SCHED|PREEMPT_RT|CGROUP_SCHED" || grep -E "RT_GROUP_SCHED|PREEMPT_RT|CGROUP_SCHED" /boot/config-$(uname -r)'
run bash -c 'stat -fc %T /sys/fs/cgroup; cat /proc/self/cgroup'
run bash -c 'find /sys/fs/cgroup -maxdepth 3 -name "cpu.rt_runtime_us" 2>/dev/null | head -5 | while read f; do echo "$f: $(cat $f)"; done; echo done'

RC_ROOT="not run"; RC_UNIT="not run"
if [ $USE_SUDO -eq 1 ]; then
  sec "4. Privileged steps (sysctl is restored on exit)"
  add "Commands: sudo sysctl -w kernel.sched_rt_runtime_us=-1 ; sudo <hello32> ; sudo systemd-run --wait --pipe -p User=$(id -un) -p LimitRTPRIO=99 <hello32>"
  OLD_RT="$(cat /proc/sys/kernel/sched_rt_runtime_us)"
  echo "setting kernel.sched_rt_runtime_us=-1 (was $OLD_RT; restored on exit)" >&2
  run sudo sysctl -w kernel.sched_rt_runtime_us=-1
  [ $LAST_RC -eq 0 ] || OLD_RT=""
  add "As root:"
  # shellcheck disable=SC2086
  run sudo $RUNNER "$WORK/hello32"; RC_ROOT=$LAST_RC
  if command -v systemd-run >/dev/null; then
    cp "$WORK/hello32" "/tmp/hello32.$$" && chmod 755 "/tmp/hello32.$$"
    add "As $(id -un) inside a transient systemd unit with LimitRTPRIO=99 (the deployment case):"
    # shellcheck disable=SC2086
    run sudo systemd-run --wait --pipe --collect -p "User=$(id -un)" -p LimitRTPRIO=99 $RUNNER "/tmp/hello32.$$"; RC_UNIT=$LAST_RC
    rm -f "/tmp/hello32.$$"
  else
    add "systemd-run not available"; RC_UNIT="skipped"
  fi
fi

sec "Verdict"
echo
case "$RC_STATIC" in
  0|3) verdict "ARM32 static exec" "PASS (binary ran, rc=$RC_STATIC)" ;;
  *)   verdict "ARM32 static exec" "FAIL (rc=$RC_STATIC; see section 2)" ;;
esac
verdict "ARM32 dynamic exec (host armel libc)" "$([ "$RC_DYN" = 0 ] || [ "$RC_DYN" = 3 ] && echo "PASS (rc=$RC_DYN)" || echo "$RC_DYN")"
verdict "RT as user (ulimit -r as is)" "$([ "$RC_STATIC" = 0 ] && echo PASS || ([ "$RC_STATIC" = 3 ] && echo "DENIED (expected while ulimit -r is 0)" || echo n/a))"
if [ $USE_SUDO -eq 1 ]; then
  verdict "RT as root, rt_runtime=-1" "$([ "$RC_ROOT" = 0 ] && echo PASS || echo "FAIL (rc=$RC_ROOT)")"
  verdict "RT in systemd unit (user, RTPRIO=99)" "$([ "$RC_UNIT" = 0 ] && echo PASS || echo "FAIL (rc=$RC_UNIT): check cpu.rt_runtime_us / RT_GROUP_SCHED")"
else
  verdict "privileged RT checks" "not run (use --sudo)"
fi
printf '%s\n' "$R" > "$OUT"
echo; echo "report: $OUT"
